name: Postgresdb update

on:
  push:
    branches:
      - DjangoPostgresdb

    paths:
    - readmeforpostgresqlupdate.md
env:
  AZURE_POSTGRESQL_SERVERNAME: vijaydjangopostgres.postgres.database.azure.com 

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
     - uses: actions/checkout@v2.3.2
     - uses: Azure/login@v1
       with:
         creds: ${{ secrets.DEPLOYGITHUB }}
     - uses: azure/postgresql@v1
       with:
         connection-string: ${{ secrets.DJANGOPOSTGRESCONNECTION }}
         server-name: ${{ env.AZURE_POSTGRESQL_SERVERNAME }}
         plsql-file: "pollsdbupdate.sql"

    # Azure logout 
     - name: logout
       run: |
        az logout 
