name: PostgreSql database automation

on:
  push:
    branches:
      - AzurePostgresDatabase

    paths:
    - 'readmepostgresqlcreate.md' 

env:
  AZURE_RESOURCE_GROUP: vijaypostgresqldb               # set this to your Azure Resource group's name  
  AZURE_LOCATION: eastus                         # set this to your azure resource group location   
  AZURE_POSTGRESQL_SERVERNAME: vijaypostgresqlserver         # set postgresql Server  
  AZURE_POSTGRESQL_DATABASE: vijaypostgresdb    # set postgresql Databsae
  AZURE_POSTGRESQL_FIREWALL_IP: 0.0.0.0    # set this to all Azure IPs
  

jobs:
  azurepostgreserversetup:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.DEPLOYGITHUB }}

# Provision a Azure MYSQL Database on Azure
    - name: Azure POSTGRESQL Server creation
      uses: azure/CLI@v1
      with:
        azcliversion: latest
        inlineScript: |
          az group create --name ${{ env.AZURE_RESOURCE_GROUP }} --location ${{ env.AZURE_LOCATION }}
          az postgres server create --resource-group ${{ env.AZURE_RESOURCE_GROUP }} --name ${{ env.AZURE_POSTGRESQL_SERVERNAME }}  --location ${{ env.AZURE_LOCATION }} --admin-user ${{ secrets.POSTGREDBADMIN }} --admin-password ${{ secrets.POSTGREDBPASS }} --sku-name B_Gen5_2 
          az postgres server firewall-rule create --resource-group ${{ env.AZURE_RESOURCE_GROUP }} --server ${{ env.AZURE_POSTGRESQL_SERVERNAME }} --name AllowMyIP --start-ip-address ${{ env.AZURE_POSTGRESQL_FIREWALL_IP }} --end-ip-address ${{ env.AZURE_POSTGRESQL_FIREWALL_IP }}

# Azure logout 
    - name: logout
      run: |
        az logout 
