name: Posgres db updated

on:
  push:
    branches:
      - AzurePostgresDatabase
    paths:
    - readmeforpostgresqlupdate.md
env:
  AZURE_POSTGRESQL_SERVERNAME: vijaypostgresqlserver.postgres.database.azure.com 

jobs:
  postgresdbupdate:
    runs-on: ubuntu-latest
    
    steps:
     - uses: actions/checkout@v2.3.2
     - uses: Azure/login@v1
       with:
         creds: ${{ secrets.DEPLOYGITHUB }}
     - uses: azure/postgresql@v1
       with:
         connection-string: ${{ secrets.AZURE_POSTGRESQL_CONNECTION_STRING }}
         server-name: ${{ env.AZURE_POSTGRESQL_SERVERNAME }}
         plsql-file: "vijaypostgresql.sql"

    # Azure logout 
     - name: logout
       run: |
        az logout 
