name: Sql database automation

on:
  push:
    branches:
      - sqldb
    paths:
    - 'readmenorun.md' 

env:
  AZURE_RESOURCE_GROUP: vijaysqldb               # set this to your Azure Resource group's name  
  AZURE_LOCATION: eastus                         # set this to your azure resource group location   
  AZURE_SQL_SERVERNAME: vijaysqldbserver         # set SQL Server  
  AZURE_SQL_DATABASE: vijaysqldatabase    # set sqladmin user
  AZURE_SQLFIREWALL_IP: 0.0.0.0    # set this to all Azure IPs
  

jobs:
  azuresetup:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.DEPLOYGITHUB }}

# Provision a Azure sQL Database on Azure
    - name: Azure SQL Database creation
      uses: azure/CLI@v1
      with:
        azcliversion: latest
        inlineScript: |
          az group create --name ${{ env.AZURE_RESOURCE_GROUP }} --location eastus
          az sql server create --name ${{ env.AZURE_SQL_SERVERNAME }} --resource-group ${{ env.AZURE_RESOURCE_GROUP }} --location ${{ env.AZURE_LOCATION }} --admin-user ${{ secrets.SQLADMINUSER }}  --admin-password ${{ secrets.SQLADMINPASS }}
          az sql server firewall-rule create --resource-group ${{ env.AZURE_RESOURCE_GROUP }} --server ${{ env.AZURE_SQL_SERVERNAME }} -n AllowYourIp --start-ip-address ${{ env.AZURE_SQLFIREWALL_IP }} --end-ip-address ${{ env.AZURE_SQLFIREWALL_IP }}
          az sql db create -g ${{ env.AZURE_RESOURCE_GROUP }} -s ${{ env.AZURE_SQL_SERVERNAME }} -n ${{ env.AZURE_SQL_DATABASE }} --service-objective S0
 #        SQLDBCONNECTIONSTRINGBLANK=$(az sql db show-connection-string --client ado.net --name ${{ env.AZURE_SQL_DATABASE }} --server ${{ env.AZURE_SQL_SERVERNAME }} --output json | jq -r .)
 #        SQLDBCONNECTIONSTRINGUSER=${SQLDBCONNECTIONSTRINGBLANK/<username>/${{ secrets.SQLADMINUSER }}}
 #        SQLDBCONNECTIONSTRINGUSERPASS=${SQLDBCONNECTIONSTRINGUSER/<password>/${{ secrets.SQLADMINPASS }}}
 #        echo $SQLDBCONNECTIONSTRINGUSERPASS
 #    env:
 #      SQLCONNECTIONSTRING: $SQLDBCONNECTIONSTRINGUSERPASS           
  
 #  - uses: azure/sql-action@v1
 #    with:
 #      server-name: ${{ env.AZURE_SQL_SERVERNAME }}
 #      connection-string: ${{â€¯secret.SQLCONNECTIONSTRING }}
 #      sql-file: './vijaysqldatabase.dacpac'

    # Azure logout 
    - name: logout
      run: |
        az logout 
 
   
